# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: npm
    directory: /docs-app
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - docs-app

  - package-ecosystem: npm
    directory: /docs-app/pdf-server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - pdf-server
